version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - backend
    networks:
      - backend-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:password@mongo:27017/user-account?authSource=admin
      - HOST=0.0.0.0
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - backend-network
      - mongo-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    networks:
      - mongo-network

networks:
  backend-network:
    driver: bridge
  mongo-network:
    driver: bridge